This is the Default API
No arguments needed to call this API and Returns welcome message if user is logged in else unauthorized access.
---
tags:
  - Default
responses:
  500:
    description: We had some issue. Please try again.
  401:
    description: You don't have sufficient permission to make this request.
  403:
    description: You are not authorized to access this content.
  400:
    description: Please check all mandatory fields and try again.
  400:
    description: Invalid request.
  200:
    description: Welcome user
    schema:
      id: default
      properties:
        browser:
          type: string
          description: User Browser Information
          default: chrome-55.0.2883.87
        device:
          type: string
          description: User Device Information
          default: PC / Windows 10 / Chrome 55.0.2883
        message:
          type: string
          description: Response Message
          default: Unauthorized Access!
        platform:
          type: string
          description: User Access Platform Information
          default: windows
        status:
          type: string
          description: Response Status
          default: success
        status_code:
          type: int
          description: Response Status Code
          default: 200
        request_string:
          type: string
          description: User Acces String
          default: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36